### ISSUE TITLE
Babel meeting - January 28th

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/notes#81]
@babel/babel feel free to add items to the agenda!

- [ ] The future of babel-eslint (https://github.com/babel/notes/issues/81#issuecomment-456595903)
- [ ] `core-js@3`
  - [ ] How do we avoid breaking changes?
  - [ ] Should we polyfill proposals by default? Should it be opt-in using a config option?
- [ ] proposals (hzoo): issues regarding naming/upgrading/migration/etc. Would like to not use the traditional way of doing semver and just do a rename for each breaking since it's always breaking or do it based on date/sha
- [ ] Babel podcast (hzoo) - let's do it!

**Comment by kaicataldo** [comment]
I had original posted a similar message in Slack, but realized this is probably a better place for this. I would like to discuss is how the team wants to do maintenance on this project going forward.

In case you haven’t been following along with the recent happenings regarding TS and ESLint (https://eslint.org/blog/2019/01/future-typescript-eslint), there’s now a new org/monorepo called typescript-eslint (https://github.com/typescript-eslint/typescript-eslint) that contains the parser and relevant plugins for linting TS with ESLint. The org has both members of ESLint and the TS team, with the main driving force and “owner” being James Henry, who has really pushed the TS/ESLint integration up to this point.

I like this for two reasons:
1. ESLint and TS members can collaborate on the project as equals
2. It allows for much more comprehensive integration testing (this could actually be an argument for moving this into the babel/babel monorepo, since we could share fixtures across parser tests, transforms, linting, you name it!)

Wanted to gauge how people are feeling about how babel-eslint is being maintained now and what people envision for maintenance going forward.
